# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled_vertical.ui'
#
# Created: Sun Nov 26 08:53:51 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 1340)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.md_gr = QtGui.QGroupBox(self.centralwidget)
        self.md_gr.setGeometry(QtCore.QRect(20, 20, 751, 111))
        self.md_gr.setObjectName("md_gr")
        self.md_label = QtGui.QLabel(self.md_gr)
        self.md_label.setGeometry(QtCore.QRect(30, 30, 471, 24))
        self.md_label.setObjectName("md_label")
        self.md_combo = QtGui.QComboBox(self.md_gr)
        self.md_combo.setGeometry(QtCore.QRect(60, 60, 401, 30))
        self.md_combo.setObjectName("md_combo")
        self.md_combo.addItem("")
        self.md_combo.addItem("")
        self.md_combo.addItem("")
        self.md_combo.addItem("")
        self.ms_gr = QtGui.QGroupBox(self.centralwidget)
        self.ms_gr.setGeometry(QtCore.QRect(20, 140, 751, 191))
        self.ms_gr.setObjectName("ms_gr")
        self.ms_label = QtGui.QLabel(self.ms_gr)
        self.ms_label.setGeometry(QtCore.QRect(30, 30, 521, 24))
        self.ms_label.setObjectName("ms_label")
        self.ms_refer = QtGui.QToolButton(self.ms_gr)
        self.ms_refer.setGeometry(QtCore.QRect(30, 70, 36, 30))
        self.ms_refer.setObjectName("ms_refer")
        self.ms_edit = QtGui.QLineEdit(self.ms_gr)
        self.ms_edit.setGeometry(QtCore.QRect(80, 70, 381, 30))
        self.ms_edit.setObjectName("ms_edit")
        self.ms_radio1 = QtGui.QRadioButton(self.ms_gr)
        self.ms_radio1.setEnabled(False)
        self.ms_radio1.setGeometry(QtCore.QRect(30, 110, 241, 28))
        self.ms_radio1.setCheckable(False)
        self.ms_radio1.setChecked(False)
        self.ms_radio1.setObjectName("ms_radio1")
        self.ms_radio2 = QtGui.QRadioButton(self.ms_gr)
        self.ms_radio2.setEnabled(False)
        self.ms_radio2.setGeometry(QtCore.QRect(30, 150, 311, 28))
        self.ms_radio2.setCheckable(False)
        self.ms_radio2.setObjectName("ms_radio2")
        self.mp_gr = QtGui.QGroupBox(self.centralwidget)
        self.mp_gr.setGeometry(QtCore.QRect(20, 340, 751, 181))
        self.mp_gr.setObjectName("mp_gr")
        self.mp_label1 = QtGui.QLabel(self.mp_gr)
        self.mp_label1.setGeometry(QtCore.QRect(30, 40, 831, 24))
        self.mp_label1.setObjectName("mp_label1")
        self.mp_label2 = QtGui.QLabel(self.mp_gr)
        self.mp_label2.setGeometry(QtCore.QRect(60, 80, 231, 24))
        self.mp_label2.setObjectName("mp_label2")
        self.mp_label3 = QtGui.QLabel(self.mp_gr)
        self.mp_label3.setGeometry(QtCore.QRect(60, 120, 221, 24))
        self.mp_label3.setObjectName("mp_label3")
        self.mp_edit1 = QtGui.QLineEdit(self.mp_gr)
        self.mp_edit1.setGeometry(QtCore.QRect(280, 80, 251, 30))
        self.mp_edit1.setObjectName("mp_edit1")
        self.mp_edit2 = QtGui.QLineEdit(self.mp_gr)
        self.mp_edit2.setGeometry(QtCore.QRect(280, 120, 251, 30))
        self.mp_edit2.setObjectName("mp_edit2")
        self.mp_label4 = QtGui.QLabel(self.mp_gr)
        self.mp_label4.setGeometry(QtCore.QRect(550, 80, 98, 24))
        self.mp_label4.setObjectName("mp_label4")
        self.mp_label5 = QtGui.QLabel(self.mp_gr)
        self.mp_label5.setGeometry(QtCore.QRect(550, 120, 201, 24))
        self.mp_label5.setObjectName("mp_label5")
        self.bc1_gr = QtGui.QGroupBox(self.centralwidget)
        self.bc1_gr.setGeometry(QtCore.QRect(20, 540, 751, 271))
        self.bc1_gr.setObjectName("bc1_gr")
        self.bc1_button = QtGui.QPushButton(self.bc1_gr)
        self.bc1_button.setGeometry(QtCore.QRect(30, 40, 150, 46))
        self.bc1_button.setObjectName("bc1_button")
        self.bc1_label = QtGui.QLabel(self.bc1_gr)
        self.bc1_label.setGeometry(QtCore.QRect(200, 50, 501, 24))
        self.bc1_label.setObjectName("bc1_label")
        self.bc1_table = QtGui.QTableView(self.bc1_gr)
        self.bc1_table.setGeometry(QtCore.QRect(30, 140, 691, 111))
        self.bc1_table.setObjectName("bc1_table")
        self.bc1_button_2 = QtGui.QPushButton(self.bc1_gr)
        self.bc1_button_2.setGeometry(QtCore.QRect(30, 90, 150, 46))
        self.bc1_button_2.setObjectName("bc1_button_2")
        self.bc1_label_2 = QtGui.QLabel(self.bc1_gr)
        self.bc1_label_2.setGeometry(QtCore.QRect(200, 100, 501, 24))
        self.bc1_label_2.setObjectName("bc1_label_2")
        self.fw_gr = QtGui.QGroupBox(self.centralwidget)
        self.fw_gr.setGeometry(QtCore.QRect(20, 1120, 751, 91))
        self.fw_gr.setObjectName("fw_gr")
        self.fw_label = QtGui.QLabel(self.fw_gr)
        self.fw_label.setGeometry(QtCore.QRect(30, 40, 211, 24))
        self.fw_label.setObjectName("fw_label")
        self.fw_edit = QtGui.QLineEdit(self.fw_gr)
        self.fw_edit.setGeometry(QtCore.QRect(240, 40, 421, 30))
        self.fw_edit.setObjectName("fw_edit")
        self.fw_refer = QtGui.QToolButton(self.fw_gr)
        self.fw_refer.setGeometry(QtCore.QRect(680, 40, 36, 30))
        self.fw_refer.setObjectName("fw_refer")
        self.bc2_gr = QtGui.QGroupBox(self.centralwidget)
        self.bc2_gr.setGeometry(QtCore.QRect(20, 830, 751, 271))
        self.bc2_gr.setObjectName("bc2_gr")
        self.bc2_button = QtGui.QPushButton(self.bc2_gr)
        self.bc2_button.setGeometry(QtCore.QRect(30, 40, 150, 46))
        self.bc2_button.setObjectName("bc2_button")
        self.bc2_label = QtGui.QLabel(self.bc2_gr)
        self.bc2_label.setGeometry(QtCore.QRect(200, 50, 501, 24))
        self.bc2_label.setObjectName("bc2_label")
        self.bc2_table = QtGui.QTableView(self.bc2_gr)
        self.bc2_table.setGeometry(QtCore.QRect(30, 140, 691, 111))
        self.bc2_table.setObjectName("bc2_table")
        self.bc2_button_2 = QtGui.QPushButton(self.bc2_gr)
        self.bc2_button_2.setGeometry(QtCore.QRect(30, 90, 150, 46))
        self.bc2_button_2.setObjectName("bc2_button_2")
        self.bc2_label_2 = QtGui.QLabel(self.bc2_gr)
        self.bc2_label_2.setGeometry(QtCore.QRect(200, 100, 501, 24))
        self.bc2_label_2.setObjectName("bc2_label_2")
        self.run_button = QtGui.QPushButton(self.centralwidget)
        self.run_button.setGeometry(QtCore.QRect(50, 1230, 150, 46))
        self.run_button.setObjectName("run_button")
        self.close_button = QtGui.QPushButton(self.centralwidget)
        self.close_button.setGeometry(QtCore.QRect(590, 1230, 150, 46))
        self.close_button.setObjectName("close_button")
        self.pv_button = QtGui.QPushButton(self.centralwidget)
        self.pv_button.setGeometry(QtCore.QRect(230, 1230, 150, 46))
        self.pv_button.setObjectName("pv_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 794, 38))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionEdit_config_ini = QtGui.QAction(MainWindow)
        self.actionEdit_config_ini.setObjectName("actionEdit_config_ini")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionEdit_config_ini)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.md_gr.setTitle(QtGui.QApplication.translate("MainWindow", "Model definition", None, QtGui.QApplication.UnicodeUTF8))
        self.md_label.setText(QtGui.QApplication.translate("MainWindow", "What kind of model do you want to work on?", None, QtGui.QApplication.UnicodeUTF8))
        self.md_combo.setItemText(0, QtGui.QApplication.translate("MainWindow", "3D", None, QtGui.QApplication.UnicodeUTF8))
        self.md_combo.setItemText(1, QtGui.QApplication.translate("MainWindow", "Plane stress", None, QtGui.QApplication.UnicodeUTF8))
        self.md_combo.setItemText(2, QtGui.QApplication.translate("MainWindow", "Plane strain", None, QtGui.QApplication.UnicodeUTF8))
        self.md_combo.setItemText(3, QtGui.QApplication.translate("MainWindow", "Axis symmetric", None, QtGui.QApplication.UnicodeUTF8))
        self.ms_gr.setTitle(QtGui.QApplication.translate("MainWindow", "Mesh selection", None, QtGui.QApplication.UnicodeUTF8))
        self.ms_label.setText(QtGui.QApplication.translate("MainWindow", "Select a mesh from the Salome object browser", None, QtGui.QApplication.UnicodeUTF8))
        self.ms_refer.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.ms_radio1.setText(QtGui.QApplication.translate("MainWindow", "Use mesh groups", None, QtGui.QApplication.UnicodeUTF8))
        self.ms_radio2.setText(QtGui.QApplication.translate("MainWindow", "Use geometrical groups", None, QtGui.QApplication.UnicodeUTF8))
        self.mp_gr.setTitle(QtGui.QApplication.translate("MainWindow", "Material properties", None, QtGui.QApplication.UnicodeUTF8))
        self.mp_label1.setText(QtGui.QApplication.translate("MainWindow", "Young\'s modulus and Poisson ratio definitions", None, QtGui.QApplication.UnicodeUTF8))
        self.mp_label2.setText(QtGui.QApplication.translate("MainWindow", "Young\'s modulus (E)", None, QtGui.QApplication.UnicodeUTF8))
        self.mp_label3.setText(QtGui.QApplication.translate("MainWindow", "Poisson\'s ration (ν)", None, QtGui.QApplication.UnicodeUTF8))
        self.mp_label4.setText(QtGui.QApplication.translate("MainWindow", "(E >= 0)", None, QtGui.QApplication.UnicodeUTF8))
        self.mp_label5.setText(QtGui.QApplication.translate("MainWindow", "(-1 <= ν <= 0.5)", None, QtGui.QApplication.UnicodeUTF8))
        self.bc1_gr.setTitle(QtGui.QApplication.translate("MainWindow", "Boundaries conditions", None, QtGui.QApplication.UnicodeUTF8))
        self.bc1_button.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.bc1_label.setText(QtGui.QApplication.translate("MainWindow", "Adding imposed degrees of freedom on groups", None, QtGui.QApplication.UnicodeUTF8))
        self.bc1_button_2.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.bc1_label_2.setText(QtGui.QApplication.translate("MainWindow", "Removing imposed degrees of freedom on groups", None, QtGui.QApplication.UnicodeUTF8))
        self.fw_gr.setTitle(QtGui.QApplication.translate("MainWindow", "Filename for writting command file", None, QtGui.QApplication.UnicodeUTF8))
        self.fw_label.setText(QtGui.QApplication.translate("MainWindow", "Aster command file", None, QtGui.QApplication.UnicodeUTF8))
        self.fw_refer.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.bc2_gr.setTitle(QtGui.QApplication.translate("MainWindow", "Boundaries conditions", None, QtGui.QApplication.UnicodeUTF8))
        self.bc2_button.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.bc2_label.setText(QtGui.QApplication.translate("MainWindow", "Adding pressure on mesh groups", None, QtGui.QApplication.UnicodeUTF8))
        self.bc2_button_2.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.bc2_label_2.setText(QtGui.QApplication.translate("MainWindow", "Removing pressure on mesh groups", None, QtGui.QApplication.UnicodeUTF8))
        self.run_button.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.close_button.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.pv_button.setText(QtGui.QApplication.translate("MainWindow", "Paraview", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_config_ini.setText(QtGui.QApplication.translate("MainWindow", "Edit config.ini", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

